{
 "title": "AWS API Gateway CloudWatch (logs + metrics)",
 "description": "AWS API Gateway logs and metrics",
 "tags": [ "cloudwatch" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "cloudwatch" },
   {
    "name": "period",
    "label": "Period",
    "query": "1s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "region",
    "query": {}
   },
   {
    "name": "api_name",
    "label": "Api Name",
    "query": {}
   },
   {
    "name": "agw_log_groups",
    "label": "Log groups",
    "query": {}
   },
   { "name": "DS_CW", "query": "cloudwatch" }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| sort @timestamp desc\n| display @timestamp, concat(httpMethod, \" \", protocol, \" \", ip, \" \" ,status, \" \", path), @message",
     "logGroups": [
      { "arn": "$agw_log_groups", "name": "$agw_log_groups" }
     ],
     "queryMode": "Logs",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Rates (sum/$period)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "ApiName": "$api_name", "Stage": "*" },
     "label": "${PROP('MetricName')} ${PROP('Dim.Stage')} / ${PROP('Period')}s",
     "metricName": "Count",
     "namespace": "AWS/ApiGateway",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ApiName": "$api_name", "Stage": "*" },
     "label": "${PROP('MetricName')} ${PROP('Dim.Stage')} / ${PROP('Period')}s",
     "metricName": "4XXError",
     "namespace": "AWS/ApiGateway",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ApiName": "$api_name", "Stage": "*" },
     "label": "${PROP('MetricName')} ${PROP('Dim.Stage')} / ${PROP('Period')}s",
     "metricName": "5XXError",
     "namespace": "AWS/ApiGateway",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Cache (sum/$period)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "ApiName": "$api_name", "Stage": "*" },
     "label": "${PROP('MetricName')} ${PROP('Dim.Stage')} / ${PROP('Period')}s",
     "metricName": "CacheHitCount",
     "namespace": "AWS/ApiGateway",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ApiName": "$api_name", "Stage": "*" },
     "label": "${PROP('MetricName')} ${PROP('Dim.Stage')} / ${PROP('Period')}s",
     "metricName": "CacheMissCount",
     "namespace": "AWS/ApiGateway",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Latencies ($period)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "ApiName": "$api_name", "Stage": "*" },
     "label": "${PROP('Stat')} ${PROP('MetricName')} ${PROP('Dim.Stage')} / ${PROP('Period')}s",
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "ApiName": "$api_name", "Stage": "*" },
     "label": "${PROP('Stat')} ${PROP('MetricName')} ${PROP('Dim.Stage')} / ${PROP('Period')}s",
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "ApiName": "$api_name", "Stage": "*" },
     "label": "${PROP('Stat')} ${PROP('MetricName')} ${PROP('Dim.Stage')} / ${PROP('Period')}s",
     "metricName": "IntegrationLatency",
     "namespace": "AWS/ApiGateway",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "ApiName": "$api_name", "Stage": "*" },
     "label": "${PROP('Stat')} ${PROP('MetricName')} ${PROP('Dim.Stage')} / ${PROP('Period')}s",
     "metricName": "IntegrationLatency",
     "namespace": "AWS/ApiGateway",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  }
 ]
}